import { PERMISSIONS, type Permission } from './permissions';
import { ROLES, type Role } from './roles';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
    [ROLES.USER]: [PERMISSIONS.CREATE_POST],
    [ROLES.AUTHOR]: [PERMISSIONS.CREATE_POST],
    [ROLES.MODERATOR]: [
        PERMISSIONS.CREATE_POST,
        PERMISSIONS.EDIT_ANY_POST,
        PERMISSIONS.DELETE_ANY_POST,
        PERMISSIONS.DELETE_ANY_COMMENT,
    ],
    [ROLES.ADMIN]: [
        PERMISSIONS.CREATE_POST,
        PERMISSIONS.EDIT_ANY_POST,
        PERMISSIONS.DELETE_ANY_POST,
        PERMISSIONS.CREATE_CATEGORY,
        PERMISSIONS.EDIT_ANY_CATEGORY,
        PERMISSIONS.DELETE_ANY_CATEGORY,
        PERMISSIONS.DELETE_ANY_COMMENT,
        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.MANAGE_VERIFICATION,
        PERMISSIONS.VIEW_LOGS,
        PERMISSIONS.MANAGE_SUPPORT,
    ],
    [ROLES.TECH_ADMIN]: [
        PERMISSIONS.CREATE_POST,
        PERMISSIONS.EDIT_ANY_POST,
        PERMISSIONS.DELETE_ANY_POST,
        PERMISSIONS.CREATE_CATEGORY,
        PERMISSIONS.EDIT_ANY_CATEGORY,
        PERMISSIONS.DELETE_ANY_CATEGORY,
        PERMISSIONS.DELETE_ANY_COMMENT,
        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.MANAGE_VERIFICATION,
        PERMISSIONS.VIEW_LOGS,
        PERMISSIONS.MANAGE_SUPPORT,
        PERMISSIONS.MANAGE_BACKUPS,
        PERMISSIONS.RESTORE_BACKUPS,
    ],
};
